version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  configuration-service:
     build: ./configuration-service
     ports:
       - 8888:8080

  registry-service:
     build: ./registry-service
     depends_on:
       - configuration-service
     ports:
       - 8761:8080
     environment:
         - CONFIGURATION_HOST=http://configuration-service
         - CONFIGURATION_PORT=8080

  monitoring-service:
     build: ./monitoring-service
     depends_on:
       - configuration-service
       - registry-service
     ports:
       - 9999:8080
     environment:
       - CONFIGURATION_HOST=http://configuration-service
       - CONFIGURATION_PORT=8080

  light-service:
     build: ./light-service
     depends_on:
       - configuration-service
       - registry-service
       - rabbitmq
     ports:
       - 8083:8080
     environment:
       - CONFIGURATION_HOST=http://configuration-service
       - CONFIGURATION_PORT=8080
  room-service:
     build: ./room-service
     depends_on:
       - configuration-service
       - registry-service
       - rabbitmq
     ports:
       - 8081:8080
     environment:
       - CONFIGURATION_HOST=http://configuration-service
       - CONFIGURATION_PORT=8080
  power-outlet-service:
     build: ./power-outlet-service
     depends_on:
       - configuration-service
       - registry-service
       - rabbitmq
     ports:
       - 8082:8080
     environment:
       - CONFIGURATION_HOST=http://configuration-service
       - CONFIGURATION_PORT=8080

  gateway-service:
     build: ./gateway-service
     depends_on:
       - configuration-service
       - registry-service
       - rabbitmq
     ports:
       - 80:8080
     environment:
       - CONFIGURATION_HOST=http://configuration-service
       - CONFIGURATION_PORT=8080
